# -*- coding: utf-8 -*-
"""train_cost_model_colab.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zv9x38rm0LKSvzMRS0dd-Dp25qOCeIHu
"""

import joblib
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Placeholder for your actual pipeline definition
# Replace this with the code that creates your 'pipe' object
pipe = Pipeline([('scaler', StandardScaler())])

joblib.dump(pipe, '/content/model.joblib')